baseURL: "https://lclerc561.github.io"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: AP
      name: AP et Projets
      title: AP et Projets
      url: /projets/
      weight: 1
    - identifier: Stages
      name: Stages
      title: Stages
      url: /stages/
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Bonjour, je suis"
    title: "Nicolas Sarkozy"
    subtitle: "Et j'ai le plaisir de vous lire le temps des tempêtes sur audible"
    content: "En effet je suis autant passioné par les tornades que par les détournements de fond. Quelle indignité"
    image: /images/Niko.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-x-twitter
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "A propos de moi"
    image: "/images/CbonpourVous.jpg"
    content: |-
      Après ma carrière de président, je me suis interessé à l'informatique, en effet il y a une oportunité en or en terme d'arnaques, afin de pouvoir faire des sites de dropshiping, j'ai du m'instruire en suivant les meilleurs dans le domaine comme Magali Berdah et Kev Adams ainsi que de Doigby. Je code actuellement un site de vente de body pillow de Mr.Macron pour Jean Castex à Beurville. 
      
    skills:
      enable: true
      title: "Voici les différents langages que j'ai su maitriser pendant mon apprentissage:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"
        - "Php"
        - "C#"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:

      - job: "Résident à plein temps"
        company: "Prison"
        date: "Janvier 2020 - present"
        featuredLink:
          enable: true
          url: "/images/Jail.jpg"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          Pas de chance, j'ai fais un malaise vagal et à cause de certains problèmes j'ai fini en prison
          Au moins le voisinage est sympa

      - job: "Dresseur de pokemon à plein temps"
        company: "Niantic"
        date: "juillet 2016 - decembre 2018"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "/images/Trempette.jpg"
        content: |
          J'ai décider d'abandonner ma carrière de chanteur afin de pouvoir devenir un dresseur pokemon à plein temps.

      - job: "Chanteur"
        company: "Sexion Assaut"
        date: "Juin 2014 - juillet 2016"
        featuredLink:
          enable: true
          url: "/images/SEXION d’assault.png"
        content: |
          Après ma carrière de Président, je me suis penché sur le rap islamiste que je dénigrais à l'époque,
          j'ai pu integré Sexion d'Assaut en remplaçant Black M, d'ailleurs on peut me voir à 3min20 
          dans le clip de Wati by night

      - job: "Président de la République"
        company: "La France"
        date: "Mai 2007 - Mai 2012"
        content: "J'ai pû faire un stage de 5 ans en tant que résponsable managériale de service d'Etats à temps semi tertiaire partiel, enfin bref président de la République !"

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "BTS SIO"
        school:
          name: "Lycée Edmé-Bouchardon Chaumont"
          url: "https://www.btsinfo.fr/"
        date: "2022 - 2024"
      - title: "BAC général"
        school:
          name: "Lycée Diderot Langres"
        date: "2019 - 2022"



  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
